name: tso
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aom=3.9.1
  - attrs=25.1.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cmocean=4.0.3
  - colorama=0.4.6
  - colorspacious=1.1.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - double-conversion=3.3.0
  - folium=0.19.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - freexl=2.0.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.3
  - graphite2=1.3.13
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - intel-openmp=2024.2.1
  - jinja2=3.1.5
  - joblib=1.4.2
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.7
  - libcurl=8.11.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgdal-core=3.10.1
  - libglib=2.82.2
  - libgomp=14.2.0
  - libheif=1.19.5
  - libhwloc=2.11.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libpng=1.6.46
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lxml=5.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - minizip=4.0.7
  - mkl=2024.2.2
  - munkres=1.1.4
  - networkx=3.4.2
  - numpy=2.2.2
  - openjpeg=2.5.3
  - openssl=3.4.0
  - owslib=0.32.1
  - packaging=24.2
  - pandas=2.2.3
  - pathlib=1.0.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - proj=9.5.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyogrio=0.10.0
  - pyparsing=3.2.1
  - pyproj=3.7.0
  - pyside6=6.8.2
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.2
  - rasterio=1.4.3
  - rav1e=0.6.6
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=75.8.0
  - shapely=2.0.7
  - six=1.17.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sqlite=3.48.0
  - svt-av1=2.3.0
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.3.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.1.0
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6